# This is a basic workflow to help you get started with Actions

name: Deploy to S3

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: 
      - dev

jobs:
    deploy:
      name: Build, Deploy to S3 bucket
      runs-on: [ubuntu-latest]
    
      strategy:
        matrix:
          node-version: [14.16.x]
    
      steps:
        - uses: actions/checkout@v2
    
        - name: Use Node.js ${{ matrix.node-version }}
          uses: actions/setup-node@v1
          with:
            node-version: ${{ matrix.node-version }}
    
        - name: Npm install
          run: npm install
    
        - name: Build
          run: npm run build
    
        - name: Transfer to S3 for serving static
          uses: jakejarvis/s3-sync-action@master
          with:
            args: --acl public-read --follow-symlinks --delete
          env:
            AWS_S3_BUCKET: senna.world
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_REGION: ap-northeast-2
            SOURCE_DIR: 'build'
